import React from 'react';
import { PieChart, DollarSign, Calculator, ShieldCheck } from 'lucide-react';
import { useTripStore } from '../stores/useTripStore';
import { BudgetDashboard } from '../components/TravelGuide/BudgetDashboard';

export const BudgetPage: React.FC = () => {
  const { currentGuide, currentTrip } = useTripStore();

  return (
    <div className="space-y-6 max-w-6xl mx-auto p-6">
      <div>
        <h1 className="text-2xl font-extrabold text-white flex items-center gap-2">
          <PieChart className="w-6 h-6 text-indigo-400" />
          Financial Budget Analytics
        </h1>
        <p className="text-xs text-slate-400 mt-1">Detailed mathematical budget calculations generated by Budget Agent.</p>
      </div>

      {currentGuide ? (
        <BudgetDashboard guide={currentGuide} />
      ) : (
        <div className="glass-panel p-12 rounded-3xl text-center space-y-4 max-w-md mx-auto">
          <div className="w-16 h-16 rounded-2xl bg-indigo-600/20 text-indigo-400 flex items-center justify-center mx-auto">
            <Calculator className="w-8 h-8" />
          </div>
          <h3 className="text-base font-bold text-slate-200">No Active Trip Selected</h3>
          <p className="text-xs text-slate-400">Create or select a trip to view complete budget calculations.</p>
        </div>
      )}
    </div>
  );
};
